# -*- coding: utf-8 -*-
"""Copy of Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hs3fOlLm5EV7OVLSxRDA9TzY_OLSwXRN
"""

import pandas as pd
import numpy as np

# Update this path to the correct location of your file, e.g., in Google Drive
# Make sure to run the `drive.mount('/content/drive')` cell first if your file is in Google Drive.
file_path = "ashrae_db2.01.csv"

df = pd.read_csv(file_path, encoding="latin1", low_memory=False)

print("Original shape:", df.shape)

df = df.dropna(axis=1, how="all")

print("After dropping empty columns:", df.shape)

physics_columns = [
    "Air temperature (°C)",
    "Radiant temperature (°C)",
    "Operative temperature (°C)",
    "Relative humidity (%)",
    "Air velocity (m/s)",
    "Clo",
    "Met",
    "Thermal sensation",
    "Climate",
    "Season"
]

# Keep only columns that actually exist
physics_columns = [c for c in physics_columns if c in df.columns]

df_phys = df[physics_columns].copy()

print("Physics dataset shape:", df_phys.shape)

# Missing values per column
missing_per_column = df.isnull().sum()

# Missing percentage per column
missing_percentage = (missing_per_column / len(df)) * 100

# Combine into a single table
missing_summary = pd.DataFrame({
    "Missing Count": missing_per_column,
    "Missing Percentage (%)": missing_percentage
}).sort_values(by="Missing Count", ascending=False)

print("Missing values per column:")
display(missing_summary)

# Grand total missing values
total_missing = missing_per_column.sum()

print("\nGrand total missing values in dataset:", total_missing)

import pandas as pd

final_columns = [
    "Air temperature (C)",
    "Relative humidity (%)",
    "Air velocity (m/s)",
    "Clo",
    "Met",
    "Climate",
    "Season",
    "Thermal sensation"
]

# Keep only columns that exist (safety check)
final_columns = [col for col in final_columns if col in df.columns]

df_final = df[final_columns].copy()

print("Final dataset shape:", df_final.shape)
print("\nFinal columns used:")
print(df_final.columns.tolist())

# Missing values per column
missing_count = df_final.isnull().sum()

# Missing percentage per column
missing_percentage = (missing_count / len(df_final)) * 100

# Combine into summary table
missing_summary = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing Percentage (%)": missing_percentage
})

print("\nMissing values summary:")
display(missing_summary)

# Grand total missing values
total_missing = missing_count.sum()
print("\nGrand total missing values:", total_missing)

import pandas as pd

# Load dataset
df = pd.read_csv("ashrae_db2.01.csv", encoding="latin1", low_memory=False)

# Select target column
target_col = "Thermal sensation"

# Check basic info
print(df[target_col].info())

# Unique values
print("Unique values:", sorted(df[target_col].dropna().unique()))

selected_columns = [
    "Thermal sensation",          # Target
    "Air temperature (C)",        # Primary driver
    "Relative humidity (%)",      # Moisture effect
    "Air velocity (m/s)",         # Convective cooling
    "Clo",                        # Clothing insulation
    "Met"                         # Metabolic rate
]

eda_df = df[selected_columns].copy()

# Drop rows with missing values
eda_df = eda_df.dropna()

print("Clean EDA dataset shape:", eda_df.shape)

print("Missing values after cleaning:")
print(eda_df.isnull().sum())

eda_df = eda_df.rename(columns={
    "Thermal sensation": "ThermalSensation",
    "Air temperature (C)": "AirTemp",
    "Relative humidity (%)": "Humidity",
    "Air velocity (m/s)": "AirVelocity",
    "Clo": "Clo",
    "Met": "Met"
})

# Number of records (rows) after cleaning
num_records = eda_df.shape[0]

# Number of features (columns)
num_features = eda_df.shape[1]

print(f"Number of records after cleaning: {num_records}")
print(f"Number of selected features: {num_features}")

print("Original dataset shape:", df.shape)
print("Clean EDA dataset shape:", eda_df.shape)

retention_percentage = (eda_df.shape[0] / df.shape[0]) * 100
print(f"Data retained after cleaning: {retention_percentage:.2f}%")

eda_df.columns

import matplotlib.pyplot as plt

eda_df.hist(
    bins=30,
    figsize=(12, 10)
)
plt.suptitle("EDA Block 1: Variable Distributions", fontsize=14)
plt.show()

plt.figure(figsize=(12,6))
eda_df.boxplot()
plt.xticks(rotation=45)
plt.title("EDA Block 1: Boxplots for Outlier Detection")
plt.show()

eda_df.describe()

eda_df["ThermalSensation"].value_counts(normalize=True).sort_index() * 100

"""**Thermal sensation vs Air temperature**"""

print(eda_df[["AirTemp", "ThermalSensation"]].isnull().sum())
print("Number of records used:", eda_df.shape[0])

plt.figure()
plt.hist(eda_df["ThermalSensation"], bins=15)
plt.xlabel("Thermal Sensation")
plt.ylabel("Count")
plt.title("Distribution of Thermal Sensation (Cleaned Data)")
plt.show()

plt.figure()
plt.scatter(
    eda_df["AirTemp"],
    eda_df["ThermalSensation"],
    alpha=0.1
)
plt.xlabel("Air Temperature (°C)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation vs Air Temperature (Cleaned Data)")
plt.show()

# Sort by temperature
temp_sorted = eda_df.sort_values("AirTemp")

# Rolling mean
rolling_mean = temp_sorted["ThermalSensation"].rolling(window=800).mean()

plt.figure()
plt.plot(temp_sorted["AirTemp"], rolling_mean)
plt.xlabel("Air Temperature (°C)")
plt.ylabel("Thermal Sensation (Rolling Mean)")
plt.title("Smoothed Trend: Thermal Sensation vs Air Temperature")
plt.show()

import numpy as np

eda_df["TempBin"] = pd.cut(
    eda_df["AirTemp"],
    bins=np.arange(
        eda_df["AirTemp"].min(),
        eda_df["AirTemp"].max() + 1,
        1
    )
)

plt.figure(figsize=(14,5))
eda_df.boxplot(
    column="ThermalSensation",
    by="TempBin",
    showfliers=False
)
plt.xticks(rotation=90)
plt.xlabel("Air Temperature Bin (°C)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation Across Air Temperature Bins")
plt.suptitle("")
plt.show()

fixed_temp = eda_df[
    (eda_df["AirTemp"] >= 24) & (eda_df["AirTemp"] <= 26)
]

plt.figure()
plt.hist(fixed_temp["ThermalSensation"], bins=15)
plt.xlabel("Thermal Sensation")
plt.ylabel("Count")
plt.title("Thermal Sensation at Fixed Temperature (24–26 °C)")
plt.show()

print("Records in 24–26 °C range:", fixed_temp.shape[0])

from scipy.stats import pearsonr, spearmanr

pearson_corr, _ = pearsonr(
    eda_df["AirTemp"],
    eda_df["ThermalSensation"]
)

spearman_corr, _ = spearmanr(
    eda_df["AirTemp"],
    eda_df["ThermalSensation"]
)

print(f"Pearson correlation (cleaned): {pearson_corr:.3f}")
print(f"Spearman correlation (cleaned): {spearman_corr:.3f}")

extreme_cases = eda_df[
    (eda_df["AirTemp"] > 30) &
    (eda_df["ThermalSensation"] < -1)
]

print("Cold sensation at high temperatures:", extreme_cases.shape[0])

eda_df.drop(columns=["TempBin"], inplace=True)

"""**Thermal sensation vs Air velocity**"""

print(eda_df[["AirVelocity", "ThermalSensation"]].isnull().sum())
print("Records used:", eda_df.shape[0])

plt.figure()
plt.hist(eda_df["AirVelocity"], bins=30)
plt.xlabel("Air Velocity (m/s)")
plt.ylabel("Count")
plt.title("Distribution of Air Velocity (Cleaned Data)")
plt.show()

plt.figure()
plt.scatter(
    eda_df["AirVelocity"],
    eda_df["ThermalSensation"],
    alpha=0.1
)
plt.xlabel("Air Velocity (m/s)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation vs Air Velocity")
plt.show()

vel_sorted = eda_df.sort_values("AirVelocity")

rolling_mean_vel = vel_sorted["ThermalSensation"].rolling(window=800).mean()

plt.figure()
plt.plot(vel_sorted["AirVelocity"], rolling_mean_vel)
plt.xlabel("Air Velocity (m/s)")
plt.ylabel("Thermal Sensation (Rolling Mean)")
plt.title("Smoothed Trend: Thermal Sensation vs Air Velocity")
plt.show()

eda_df["VelocityBin"] = pd.cut(
    eda_df["AirVelocity"],
    bins=np.linspace(
        eda_df["AirVelocity"].min(),
        eda_df["AirVelocity"].max(),
        15
    )
)

plt.figure(figsize=(14,5))
eda_df.boxplot(
    column="ThermalSensation",
    by="VelocityBin",
    showfliers=False
)
plt.xticks(rotation=90)
plt.xlabel("Air Velocity Bin (m/s)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation Across Air Velocity Bins")
plt.suptitle("")
plt.show()

still_air = eda_df[eda_df["AirVelocity"] <= 0.1]

plt.figure()
plt.hist(still_air["ThermalSensation"], bins=15)
plt.xlabel("Thermal Sensation")
plt.ylabel("Count")
plt.title("Thermal Sensation under Still Air Conditions")
plt.show()

print("Records in still air:", still_air.shape[0])

from scipy.stats import pearsonr, spearmanr

p_corr, _ = pearsonr(
    eda_df["AirVelocity"],
    eda_df["ThermalSensation"]
)

s_corr, _ = spearmanr(
    eda_df["AirVelocity"],
    eda_df["ThermalSensation"]
)

print(f"Pearson correlation: {p_corr:.3f}")
print(f"Spearman correlation: {s_corr:.3f}")

eda_df.drop(columns=["VelocityBin"], inplace=True)

eda_df.columns

"""**Thermal sensation vs Relative humidity**"""

print(eda_df[["Humidity", "ThermalSensation"]].isnull().sum())
print("Records used:", eda_df.shape[0])

plt.figure()
plt.hist(eda_df["Humidity"], bins=30, color="skyblue", edgecolor="black")
plt.xlabel("Relative Humidity (%)")
plt.ylabel("Count")
plt.title("Distribution of Relative Humidity")
plt.show()

plt.figure()
plt.scatter(
    eda_df["Humidity"],
    eda_df["ThermalSensation"],
    alpha=0.1,
    color="green"
)
plt.xlabel("Relative Humidity (%)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation vs Relative Humidity")
plt.show()

rh_sorted = eda_df.sort_values("Humidity")

rolling_mean_rh = rh_sorted["ThermalSensation"].rolling(window=800).mean()

plt.figure()
plt.plot(rh_sorted["Humidity"], rolling_mean_rh, color="red")
plt.xlabel("Relative Humidity (%)")
plt.ylabel("Thermal Sensation (Rolling Mean)")
plt.title("Smoothed Trend: Thermal Sensation vs Relative Humidity")
plt.show()

eda_df["RHBin"] = pd.cut(
    eda_df["Humidity"],
    bins=np.arange(
        eda_df["Humidity"].min(),
        eda_df["Humidity"].max() + 5,
        5
    )
)

plt.figure(figsize=(14,5))
eda_df.boxplot(
    column="ThermalSensation",
    by="RHBin",
    showfliers=False
)
plt.xticks(rotation=90)
plt.xlabel("Relative Humidity Bin (%)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation Across Relative Humidity Bins")
plt.suptitle("")
plt.show()

eda_df.drop(columns=["RHBin"], inplace=True)

fixed_rh = eda_df[(eda_df["Humidity"] >= 40) & (eda_df["Humidity"] <= 50)]

plt.figure()
plt.hist(fixed_rh["ThermalSensation"], bins=15, color="orange", edgecolor="black")
plt.xlabel("Thermal Sensation")
plt.ylabel("Count")
plt.title("Thermal Sensation at Fixed Humidity (40–50%)")
plt.show()

print("Number of records in 40–50% RH:", fixed_rh.shape[0])

from scipy.stats import pearsonr, spearmanr

p_corr, _ = pearsonr(
    eda_df["Humidity"],
    eda_df["ThermalSensation"]
)

s_corr, _ = spearmanr(
    eda_df["Humidity"],
    eda_df["ThermalSensation"]
)

print(f"Pearson correlation (Humidity): {p_corr:.3f}")
print(f"Spearman correlation (Humidity): {s_corr:.3f}")

"""**Thermal sensation vs Clothing insulation**"""

print(eda_df[["Clo", "ThermalSensation"]].isnull().sum())
print("Records used:", eda_df.shape[0])

plt.figure()
plt.hist(eda_df["Clo"], bins=30, edgecolor="black")
plt.xlabel("Clothing Insulation (Clo)")
plt.ylabel("Count")
plt.title("Distribution of Clothing Insulation")
plt.show()

plt.figure()
plt.scatter(
    eda_df["Clo"],
    eda_df["ThermalSensation"],
    alpha=0.2
)
plt.xlabel("Clothing Insulation (Clo)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation vs Clothing Insulation")
plt.show()

clo_sorted = eda_df.sort_values("Clo")
rolling_mean_clo = clo_sorted["ThermalSensation"].rolling(window=500).mean()

plt.figure()
plt.plot(clo_sorted["Clo"], rolling_mean_clo, color="red")
plt.xlabel("Clothing Insulation (Clo)")
plt.ylabel("Thermal Sensation (Rolling Mean)")
plt.title("Smoothed Trend: Thermal Sensation vs Clo")
plt.show()

eda_df["CloBin"] = pd.cut(
    eda_df["Clo"],
    bins=np.arange(
        eda_df["Clo"].min(),
        eda_df["Clo"].max() + 0.1,
        0.1
    )
)

plt.figure(figsize=(14,5))
eda_df.boxplot(
    column="ThermalSensation",
    by="CloBin",
    showfliers=False
)
plt.xticks(rotation=90)
plt.xlabel("Clothing Insulation Bin (Clo)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation Across Clothing Insulation Bins")
plt.suptitle("")
plt.show()

eda_df.drop(columns=["CloBin"], inplace=True)

fixed_clo = eda_df[(eda_df["Clo"] >= 0.5) & (eda_df["Clo"] <= 0.6)]

plt.figure()
plt.hist(fixed_clo["ThermalSensation"], bins=15, edgecolor="black")
plt.xlabel("Thermal Sensation")
plt.ylabel("Count")
plt.title("Thermal Sensation at Fixed Clo (0.5–0.6)")
plt.show()

print("Records in fixed Clo range:", fixed_clo.shape[0])

from scipy.stats import pearsonr, spearmanr

p_corr, _ = pearsonr(
    eda_df["Clo"],
    eda_df["ThermalSensation"]
)

s_corr, _ = spearmanr(
    eda_df["Clo"],
    eda_df["ThermalSensation"]
)

print(f"Pearson correlation (Clo): {p_corr:.3f}")
print(f"Spearman correlation (Clo): {s_corr:.3f}")

"""**Thermal sensation vs Metabolic rate**"""

plt.figure()
plt.hist(eda_df["Met"], bins=30, edgecolor="black")
plt.xlabel("Metabolic Rate (Met)")
plt.ylabel("Count")
plt.title("Distribution of Metabolic Rate")
plt.show()

plt.figure()
plt.scatter(
    eda_df["Met"],
    eda_df["ThermalSensation"],
    alpha=0.2
)
plt.xlabel("Metabolic Rate (Met)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation vs Metabolic Rate")
plt.show()

met_sorted = eda_df.sort_values("Met")
rolling_mean_met = met_sorted["ThermalSensation"].rolling(window=500).mean()

plt.figure()
plt.plot(met_sorted["Met"], rolling_mean_met, color="red")
plt.xlabel("Metabolic Rate (Met)")
plt.ylabel("Thermal Sensation (Rolling Mean)")
plt.title("Smoothed Trend: Thermal Sensation vs Met")
plt.show()

eda_df["MetBin"] = pd.cut(
    eda_df["Met"],
    bins=np.arange(
        eda_df["Met"].min(),
        eda_df["Met"].max() + 0.1,
        0.1
    )
)

plt.figure(figsize=(14,5))
eda_df.boxplot(
    column="ThermalSensation",
    by="MetBin",
    showfliers=False
)
plt.xticks(rotation=90)
plt.xlabel("Metabolic Rate Bin (Met)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation Across Metabolic Rate Bins")
plt.suptitle("")
plt.show()

eda_df.drop(columns=["MetBin"], inplace=True)

fixed_met = eda_df[(eda_df["Met"] >= 1.0) & (eda_df["Met"] <= 1.2)]

plt.figure()
plt.hist(fixed_met["ThermalSensation"], bins=15, edgecolor="black")
plt.xlabel("Thermal Sensation")
plt.ylabel("Count")
plt.title("Thermal Sensation at Fixed Met (1.0–1.2)")
plt.show()

print("Records in fixed Met range:", fixed_met.shape[0])

from scipy.stats import pearsonr, spearmanr

p_corr, _ = pearsonr(
    eda_df["Met"],
    eda_df["ThermalSensation"]
)

s_corr, _ = spearmanr(
    eda_df["Met"],
    eda_df["ThermalSensation"]
)

print(f"Pearson correlation (Met): {p_corr:.3f}")
print(f"Spearman correlation (Met): {s_corr:.3f}")

"""Correlation heat map"""

import seaborn as sns

core_vars = [
    "AirTemp",
    "Humidity",
    "AirVelocity",
    "Clo",
    "Met",
    "ThermalSensation"
]

plt.figure(figsize=(8,6))
sns.heatmap(
    eda_df[core_vars].corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Correlation Heatmap (Core Variables)")
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X = eda_df[core_vars[:-1]]

X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
pca_components = pca.fit_transform(X_scaled)

plt.figure()
plt.scatter(
    pca_components[:,0],
    pca_components[:,1],
    alpha=0.1
)
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA of Environmental & Human Variables")
plt.show()

print("Explained variance:", pca.explained_variance_ratio_)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)
labels = kmeans.fit_predict(X_scaled)

plt.figure()
plt.scatter(
    pca_components[:,0],
    pca_components[:,1],
    c=labels,
    alpha=0.3
)
plt.title("Unsupervised Clustering (PCA space)")
plt.show()

"""**Temperature × Met Interaction**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Rename for convenience (optional)
eda_df = eda_df.rename(columns={
    "Air temperature (C)": "AirTemp",
    "Thermal sensation": "ThermalSensation"
})

# Define temperature bins
temp_bins = [ -10, 18, 25, 40 ]
temp_labels = ["Cold", "Neutral", "Warm"]

eda_df["TempBin"] = pd.cut(
    eda_df["AirTemp"],
    bins=temp_bins,
    labels=temp_labels
)

# Check distribution
print(eda_df["TempBin"].value_counts())

plt.figure(figsize=(8,6))

for label in temp_labels:
    subset = eda_df[eda_df["TempBin"] == label]
    plt.scatter(
        subset["Met"],
        subset["ThermalSensation"],
        alpha=0.25,
        label=label
    )

plt.xlabel("Metabolic Rate (Met)")
plt.ylabel("Thermal Sensation")
plt.title("Temperature × Met Interaction")
plt.legend(title="Temperature Range")
plt.show()

plt.figure(figsize=(8,6))

for label in temp_labels:
    subset = eda_df[eda_df["TempBin"] == label].sort_values("Met")
    rolling_mean = subset["ThermalSensation"].rolling(window=300).mean()

    plt.plot(
        subset["Met"],
        rolling_mean,
        label=label
    )

plt.xlabel("Metabolic Rate (Met)")
plt.ylabel("Thermal Sensation (Rolling Mean)")
plt.title("Interaction Effect: Met across Temperature Ranges")
plt.legend(title="Temperature Range")
plt.show()

from scipy.stats import pearsonr

for label in temp_labels:
    subset = eda_df[eda_df["TempBin"] == label]
    corr, _ = pearsonr(subset["Met"], subset["ThermalSensation"])
    print(f"Pearson (Met vs Sensation) at {label} temperatures: {corr:.3f}")

"""**Temperature × Clothing interaction**"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Create temperature bins
temp_bins = pd.cut(
    eda_df["AirTemp"],
    bins=[-10, 20, 26, 45],
    labels=["Cold", "Neutral", "Warm"]
)

eda_df["TempRange"] = temp_bins

plt.figure(figsize=(10,6))

for label, color in zip(["Cold", "Neutral", "Warm"], ["blue", "orange", "green"]):
    subset = eda_df[eda_df["TempRange"] == label]
    plt.scatter(
        subset["Clo"],
        subset["ThermalSensation"],
        alpha=0.25,
        label=label
    )

plt.xlabel("Clothing Insulation (Clo)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation vs Clothing (Clo)\nAcross Temperature Ranges")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,6))

for label, color in zip(["Cold", "Neutral", "Warm"], ["blue", "orange", "green"]):
    subset = eda_df[eda_df["TempRange"] == label].sort_values("Clo")

    rolling_mean = subset["ThermalSensation"].rolling(
        window=300,
        min_periods=50
    ).mean()

    plt.plot(
        subset["Clo"],
        rolling_mean,
        color=color,
        label=label
    )

plt.xlabel("Clothing Insulation (Clo)")
plt.ylabel("Thermal Sensation (Rolling Mean)")
plt.title("Interaction Effect: Clothing across Temperature Ranges")
plt.legend()
plt.grid(True)
plt.show()

from scipy.stats import pearsonr, spearmanr

for label in ["Cold", "Neutral", "Warm"]:
    subset = eda_df[eda_df["TempRange"] == label]

    pearson = pearsonr(subset["Clo"], subset["ThermalSensation"])[0]
    spearman = spearmanr(subset["Clo"], subset["ThermalSensation"])[0]

    print(f"{label} temperatures:")
    print(f"  Pearson correlation:  {pearson:.3f}")
    print(f"  Spearman correlation: {spearman:.3f}\n")

"""**Temperature × Air Velocity Interaction**"""

plt.figure(figsize=(10,6))

for label, color in zip(["Cold", "Neutral", "Warm"], ["blue", "orange", "green"]):
    subset = eda_df[eda_df["TempRange"] == label]

    plt.scatter(
        subset["AirVelocity"],
        subset["ThermalSensation"],
        alpha=0.25,
        label=label
    )

plt.xlabel("Air Velocity (m/s)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation vs Air Velocity\nAcross Temperature Ranges")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,6))

for label, color in zip(["Cold", "Neutral", "Warm"], ["blue", "orange", "green"]):
    subset = eda_df[eda_df["TempRange"] == label].sort_values("AirVelocity")

    rolling_mean = subset["ThermalSensation"].rolling(
        window=300,
        min_periods=50
    ).mean()

    plt.plot(
        subset["AirVelocity"],
        rolling_mean,
        color=color,
        label=label
    )

plt.xlabel("Air Velocity (m/s)")
plt.ylabel("Thermal Sensation (Rolling Mean)")
plt.title("Interaction Effect: Air Velocity across Temperature Ranges")
plt.legend()
plt.grid(True)
plt.show()

from scipy.stats import pearsonr, spearmanr

for label in ["Cold", "Neutral", "Warm"]:
    subset = eda_df[eda_df["TempRange"] == label]

    pearson = pearsonr(subset["AirVelocity"], subset["ThermalSensation"])[0]
    spearman = spearmanr(subset["AirVelocity"], subset["ThermalSensation"])[0]

    print(f"{label} temperatures:")
    print(f"  Pearson correlation:  {pearson:.3f}")
    print(f"  Spearman correlation: {spearman:.3f}\n")

"""**Temperature × Relative Humidity Interaction**"""

plt.figure(figsize=(10,6))

for label, color in zip(["Cold", "Neutral", "Warm"], ["blue", "orange", "green"]):
    subset = eda_df[eda_df["TempRange"] == label]

    plt.scatter(
        subset["Humidity"],
        subset["ThermalSensation"],
        alpha=0.25,
        label=label
    )

plt.xlabel("Relative Humidity (%)")
plt.ylabel("Thermal Sensation")
plt.title("Thermal Sensation vs Relative Humidity\nAcross Temperature Ranges")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,6))

for label, color in zip(["Cold", "Neutral", "Warm"], ["blue", "orange", "green"]):
    subset = eda_df[eda_df["TempRange"] == label].sort_values("Humidity")

    rolling_mean = subset["ThermalSensation"].rolling(
        window=300,
        min_periods=50
    ).mean()

    plt.plot(
        subset["Humidity"],
        rolling_mean,
        color=color,
        label=label
    )

plt.xlabel("Relative Humidity (%)")
plt.ylabel("Thermal Sensation (Rolling Mean)")
plt.title("Interaction Effect: Humidity across Temperature Ranges")
plt.legend()
plt.grid(True)
plt.show()

for label in ["Cold", "Neutral", "Warm"]:
    subset = eda_df[eda_df["TempRange"] == label]

    pearson = pearsonr(subset["Humidity"], subset["ThermalSensation"])[0]
    spearman = spearmanr(subset["Humidity"], subset["ThermalSensation"])[0]

    print(f"{label} temperatures:")
    print(f"  Pearson correlation:  {pearson:.3f}")
    print(f"  Spearman correlation: {spearman:.3f}\n")

eda_df.columns

eda_df.drop(columns=["TempBin"], inplace=True)
eda_df.drop(columns=["TempRange"], inplace=True)

eda_df.columns

"""Creating labels for classification"""

import numpy as np

# Create comfort class labels
def comfort_label(tsv):
    if tsv <= -1.0:
        return "Cold"
    elif -1.0 < tsv < 1.0:
        return "Neutral"
    else:
        return "Warm"

eda_df["ComfortClass"] = eda_df["ThermalSensation"].apply(comfort_label)

eda_df[["ThermalSensation", "ComfortClass"]].head(10)

class_counts = eda_df["ComfortClass"].value_counts()
class_percent = eda_df["ComfortClass"].value_counts(normalize=True) * 100

class_summary = class_counts.to_frame(name="Count")
class_summary["Percentage (%)"] = class_percent.round(2)

class_summary

"""feature label preparation"""

final_features = [
    "AirTemp",
    "Humidity",
    "AirVelocity",
    "Clo",
    "Met"
]

target = "ComfortClass"

ml_df = eda_df[final_features + [target]]

ml_df.isnull().sum()

print("Final dataset shape:", ml_df.shape)

X = ml_df[final_features]
y = ml_df[target]

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Check mapping
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
label_mapping

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

import numpy as np

print("Train class distribution:", np.bincount(y_train) / len(y_train))
print("Test class distribution:", np.bincount(y_test) / len(y_test))

"""Baseline ML"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(
    multi_class="multinomial",
    solver="lbfgs",
    max_iter=1000,
    random_state=42
)

log_reg.fit(X_train_scaled, y_train)

y_pred = log_reg.predict(X_test_scaled)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=label_encoder.classes_
)

disp.plot(cmap="Blues")
plt.title("Baseline Logistic Regression Confusion Matrix")
plt.show()

from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred,
    target_names=label_encoder.classes_
))

import pandas as pd

coef_df = pd.DataFrame(
    log_reg.coef_,
    columns=final_features,
    index=label_encoder.classes_
)

coef_df

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Build model
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42
)

# Train
rf_model.fit(X_train, y_train)

# Predict
y_pred_rf = rf_model.predict(X_test)

# Accuracy
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

# Classification report
print(classification_report(y_test, y_pred_rf))

# Confusion matrix
print(confusion_matrix(y_test, y_pred_rf))

import pandas as pd

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print(importance)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Parameter grid
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

rf = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    n_jobs=-1,
    verbose=1,
    scoring='accuracy'
)

grid_search.fit(X_train, y_train)

# Best model
best_rf = grid_search.best_estimator_

print("Best Parameters:", grid_search.best_params_)

from sklearn.metrics import accuracy_score, classification_report

y_pred_best = best_rf.predict(X_test)

print("Tuned Random Forest Accuracy:", accuracy_score(y_test, y_pred_best))
print(classification_report(y_test, y_pred_best))